export { default as Header } from "./Header";
export { default as App } from "./App";
export { default as Button } from "./Areas/Button";
export { default as Banner } from "./Areas/Banner";
export { default as MovieList } from "./Areas/MovieList";
export { default as MovieCard } from "./Areas/MovieCard";
export { default as Footer } from "./Footer";
export { default as Register } from "./Areas/Register";
export { default as Login } from "./Areas/Login";
